version: '3'

services:

  app:
    build: .
    container_name: app
    networks:
      - node_network
    volumes:
      - .:/usr/src/app
    tty: true
    ports:
      - "3000:3000"

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node_network

networks:
  node_network:
    driver: bridge

    
